# Generated by Django 6.0 on 2025-12-15 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_student_date_of_birth_alter_student_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Miqdori (so'mda)")),
                ('due_date', models.DateField(verbose_name="To'lov muddati")),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name="To'lov qilingan sana")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda (Qarzdorlik)'), ('completed', "To'langan"), ('overdue', "Muddati o'tgan"), ('canceled', 'Bekor qilingan')], default='pending', max_length=10, verbose_name='Holati')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['due_date', 'status'],
            },
        ),
    ]
