# Generated by Django 6.0 on 2025-12-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_simplestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Tug‘ilgan sana'),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="Oxirgi to'lov summasi"),
        ),
    ]
