# Generated by Django 5.2.6 on 2025-09-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('boss', 'Boss'), ('teacher', 'Teacher')], default='teacher', max_length=20),
        ),
    ]
