# Generated by Django 5.2.6 on 2025-09-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_avatar_alter_customuser_first_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('boss', 'Boss'), ('teacher', 'Teacher')], default='boss', max_length=20, verbose_name='Rol'),
        ),
    ]
