# Generated by Django 5.2.6 on 2025-09-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('boss', 'Boss'), ('teacher', 'Teacher')], default='teacher', max_length=20, verbose_name='Rol'),
        ),
    ]
