# Generated by Django 6.0 on 2025-12-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('boss', 'Boss'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=20, verbose_name='Rol'),
        ),
    ]
