# Generated by Django 5.2.6 on 2025-09-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Bajarilmagan'), ('done', 'Bajarilgan')], default='pending', max_length=10),
        ),
    ]
