# Generated by Django 6.0 on 2025-12-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_simplestudent'),
        ('tasks', '0003_remove_task_assigned_teacher_remove_task_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Vazifa', 'verbose_name_plural': 'Vazifalar'},
        ),
        migrations.AddField(
            model_name='task',
            name='target_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='students.student', verbose_name="O'quvchi"),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Bajarilgan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Bajarilgan sana')),
                ('feedback', models.TextField(blank=True, verbose_name='Izoh/Baholash')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='students.student', verbose_name="O'quvchi")),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.task', verbose_name='Vazifa')),
            ],
            options={
                'verbose_name': 'Vazifa tayinlash',
                'verbose_name_plural': 'Vazifalar tayinlash',
                'unique_together': {('task', 'student')},
            },
        ),
    ]
