# Generated by Django 6.0 on 2025-12-17 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_alter_lesson_options_alter_lesson_duration_minutes_and_more'),
        ('students', '0003_student_date_of_birth_alter_student_payment'),
        ('tasks', '0004_alter_task_options_task_target_student_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date', 'title'], 'verbose_name': 'Vazifa', 'verbose_name_plural': 'Vazifalar'},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Bajarilmagan'), ('done', 'Bajarilgan')], default='pending', max_length=10, verbose_name='Umumiy Holati'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='groups.group', verbose_name='Guruh'),
        ),
        migrations.AlterField(
            model_name='task',
            name='target_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='students.student', verbose_name="O'quvchi (Shaxsiy)"),
        ),
    ]
