# Generated by Django 5.2.6 on 2025-09-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='group',
            name='student_count',
        ),
        migrations.AddField(
            model_name='group',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
