# Generated by Django 6.0 on 2025-12-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_options_group_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Guruh', 'verbose_name_plural': 'Guruhlar'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='students_count',
        ),
        migrations.AddField(
            model_name='group',
            name='type',
            field=models.CharField(choices=[('IT', "IT yo'nalishi"), ('Language', 'Tillar'), ('Math', 'Aniq fanlar'), ('Other', 'Boshqalar')], default='IT', max_length=50, verbose_name="Yo'nalishi"),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="So'nggi o'zgarish"),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol / Ochiq'),
        ),
    ]
