# Generated by Django 6.0 on 2025-12-15 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_alter_group_options_remove_group_students_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('duration_minutes', models.PositiveIntegerField(default=90, verbose_name='Davomiyligi (daqiqada)')),
                ('topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dars mavzusi / nomi')),
                ('lesson_type', models.CharField(choices=[('regular', 'Oddiy dars'), ('test', 'Nazorat/Imtihon'), ('extra', "Qo'shimcha dars")], default='regular', max_length=10, verbose_name='Dars turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='groups.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['start_time'],
            },
        ),
    ]
