# Generated by Django 5.2.6 on 2025-09-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_name', models.CharField(default='TutorCRM', max_length=100)),
                ('language', models.CharField(choices=[('uz', 'O‘zbekcha'), ('en', 'English')], default='uz', max_length=20)),
                ('currency', models.CharField(default='UZS', max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
